import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as sdk from './index.mjs';
assert.equal(sdk.negotiate(sdk.API_VERSION).mutation_authorized,false);
assert.throws(()=>sdk.negotiate('future'),/^Error: UNSUPPORTED_SDK_VERSION$/);
assert.throws(()=>sdk.decode(Buffer.from('{}')),/^Error: INVALID_SNAPSHOT$/);
assert.throws(()=>sdk.capsuleImport(Buffer.from('bad')),/^Error: INVALID_CAPSULE$/);
const state=sdk.decode(fs.readFileSync(new URL('./example.json',import.meta.url)));
assert.deepEqual(sdk.capsuleImport(sdk.capsuleExport(state)),state);
console.log('SDK: 5 contract checks passed');
